/** Build the package-private SDK extension; installed consumers never patch node_modules. */
import { readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const spec = JSON.parse(readFileSync(resolve(root, "../sdk/upstream.json"), "utf8")).typescript;
const source = readFileSync(resolve(dirname(require.resolve("mem0ai/oss")), "index.mjs"));
if (createHash("sha256").update(source).digest("hex") !== spec.sha256) throw new Error("Mem0 source hash mismatch; review the SDK update before building");
let text = source.toString();
const before = "var Memory = class _Memory {\n  constructor(config = {}) {";
if (!text.includes(before)) throw new Error("missing Mem0 constructor");
text = text.replace(before, `var Memory = class _Memory {
  constructor(config = {}, providers = {}) {
    for (const [value, methods] of [[providers.llm, ["generateResponse", "generateChat"]], [providers.embedder, ["embed", "embedBatch"]]]) {
      if (value !== undefined && (value === null || methods.some(name => typeof value[name] !== "function"))) throw new TypeError("invalid injected Mem0 provider");
    }
    this.injectedProviders = Object.freeze({ ...providers });
    this.providerBinding = Object.freeze({ llm: providers.llm ? "injected" : "native", embedder: providers.embedder ? "injected" : "native" });`);
for (const [field, factory] of [["embedder", "EmbedderFactory"], ["llm", "LLMFactory"]]) {
  const pattern = `this.${field} = ${factory}.create(`;
  if (text.split(pattern).length !== 3) throw new Error("unexpected Mem0 initialization/reset shape");
  text = text.replaceAll(pattern, `this.${field} = this.injectedProviders.${field} ?? ${factory}.create(`);
}
const ready = `  async ready() {
    await this._initPromise;
    if (this._initError) {
      const error = this._initError;
      // Only handles created by this SDK are released; caller-supplied clients remain owned by the caller.
      for (const resource of [this.db, this.config.vectorStore.config.client ? undefined :
        (this.config.vectorStore.provider === "memory" ? this.vectorStore?.db : this.vectorStore)]) {
        try { await resource?.close?.(); } catch { /* Preserve the initialization failure. */ }
      }
      throw error;
    }
    return this;
  }
`;
const anchor = "  async _autoInitialize() {";
if (text.split(anchor).length !== 2) throw new Error("unexpected Mem0 initialization hook");
text = text.replace(anchor, ready + anchor).replace(/\n\/\/# sourceMappingURL=.*$/m, "");
writeFileSync(resolve(root, "dist/sdk-memory.js"), "// Derived from mem0ai 3.1.7 (Apache-2.0). PurrA adds constructor/reset provider injection.\n// Generated by scripts/build-sdk.mjs; see THIRD_PARTY_NOTICES.md.\n" + text);
copyFileSync(resolve(root, "src/sdk-memory.d.ts"), resolve(root, "dist/sdk-memory.d.ts"));
