"""Regenerate the private Mem0 module from the pinned installed SDK, never at runtime."""
import argparse
import hashlib
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument("source", type=Path, help="Unmodified mem0/memory/main.py from mem0ai 2.0.19")
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
spec = json.loads((root.parent / "sdk/upstream.json").read_text())["python"]
original = args.source.read_bytes()
if hashlib.sha256(original).hexdigest() != spec["sha256"]:
    raise SystemExit("Mem0 source hash mismatch; review the SDK update before regenerating")
text = original.decode()
before = 'class Memory(MemoryBase):\n    def __init__(self, config: MemoryConfig = MemoryConfig()):\n        self.config = config'
after = '''class Memory(MemoryBase):
    def __init__(self, config: MemoryConfig = MemoryConfig(), *, llm=None, embedder=None):
        for value, methods in ((llm, ("generate_response",)), (embedder, ("embed", "embed_batch"))):
            if value is not None and any(not callable(getattr(value, name, None)) for name in methods):
                raise TypeError("invalid injected Mem0 provider")
        self.config = config'''
assert text.count(before) == 1
text = text.replace(before, after)
text = text.replace('self.embedding_model = EmbedderFactory.create(', 'self.embedding_model = embedder if embedder is not None else EmbedderFactory.create(', 1)
text = text.replace('self.llm = LlmFactory.create(self.config.llm.provider, self.config.llm.config)', 'self.llm = llm if llm is not None else LlmFactory.create(self.config.llm.provider, self.config.llm.config)', 1)
start = text.index("        self.embedding_model =", text.index("class Memory(MemoryBase):"))
end = text.index("\n    @property", start)
body = text[start:end]
text = text[:start] + """        self.provider_binding = {"llm": "injected" if llm is not None else "native", "embedder": "injected" if embedder is not None else "native"}
        try:
""" + "\n".join("    " + line if line else line for line in body.split("\n")) + """
        except BaseException:
            resources = [getattr(self, "db", None)]
            if self.config.vector_store.provider == "qdrant" and getattr(self.config.vector_store.config, "client", None) is None:
                resources.append(getattr(getattr(self, "vector_store", None), "client", None))
                resources.append(getattr(getattr(self, "_telemetry_vector_store", None), "client", None))
            for resource in resources:
                try:
                    if resource is not None:
                        resource.close()
                except Exception:
                    pass  # Preserve the initialization failure.
            raise
""" + text[end:]
text = '# Derived from mem0ai 2.0.19 (Apache-2.0). PurrA adds constructor provider injection.\n# Generated by scripts/sync_sdk.py; see THIRD_PARTY_NOTICES.md.\n' + text
target = root / "src/purra_mem0/_vendor/memory.py"
if args.check:
    if target.read_text() != text:
        raise SystemExit("private Mem0 module differs from the reviewed transformation")
else:
    target.write_text(text)
